---
- !ruby/object:LogfileTransfer::FileMonitorObj
  absolute_path:
  - /data/webroot/log
  - /data/abc
  dir_disallow: []
  file_disallow:
  - .*
  file_allow:
  - \.log\.
  patterns:
  - - gamestart\.log\.
    - - !ruby/object:Test {}
      - !ruby/object:Test1 {}
  - - gameexit\.log\.
    - - !ruby/object:Test {}
      - !ruby/object:Test1 {}
- !ruby/object:LogfileTransfer::FileMonitorObj
  absolute_path:
  - /data/webroot/tlog
  dir_disallow: []
  file_disallow:
  - .*
  file_allow:
  - \.log\.
  patterns:
  - - gamestart\.log\.
    - - !ruby/object:Test {}
      - !ruby/object:Test1 {}
