---
- !ruby/object:LogfileTransfer::FileMonitorObj
  absolute_path: /home
  dir_disallow: []
  file_disallow:
  - .*
  file_allow:
  - \.log\.
  patterns:
  - - gamestart
    - - !ruby/object:Test {}
      - !ruby/object:Test {}
  - - gameexit
    - - !ruby/object:Test {}
      - !ruby/object:Test {}
- !ruby/object:LogfileTransfer::FileMonitorObj
  absolute_path: /var
  dir_disallow: []
  file_disallow:
  - .*
  file_allow:
  - \.log\.
  patterns:
  - - gamestart
    - - !ruby/object:Test {}
      - !ruby/object:Test {}
